@startuml C4ContextDiagram

'Read: Richardo Niepel's excellent https://github.com/RicardoNiepel/C4-PlantUML and https://github.com/RicardoNiepel/Azure-PlantUML

hide stereotype

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2-1/dist

!includeurl AzurePuml/AzureC4Integration.puml

' Import for icons
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/General/Azure.puml
!includeurl AzurePuml/Web/AzureWebApp.puml
!includeurl AzurePuml/Compute/AzureFunction.puml
!includeurl AzurePuml/Databases/AzureSqlDatabase.puml
!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml
!includeurl AzurePuml/Storage/AzureQueueStorage.puml
!includeurl AzurePuml/Storage/AzureStorage.puml
!includeurl AzurePuml/Identity/AzureActiveDirectory.puml
!includeurl AzurePuml/DevOps/AzureApplicationInsights.puml

Person(sponsor, "Sponsor", "Equinor Employee/Consultant or External")
Person(sponsorRep, "Sponsor rep", "Equinor Employee/Consultant or External")
Person(viewer, "Viewer", "Equinor Employee/Consultant or External")
Person(vendor, "Vendor", "Companies who use Sepes to showcase their product")

Boundary(sepes, "Sepes") {
System(spa, "Sepes website", "Provides Sepes functionality to users via their web browser")
System(api, "Sepes API", "Provides Sepes functionality through API calls")
}

Azure(study, "Study", "Virtual machine(s)", "Vendor for Sepes")   
System(datasets, "Data sets", "Pool of data sets pre-approved for Sepes studies")
System(datasetStudy, "Study data set", "Study specific data set")0

Boundary(bb, "Toolbox for Sepes") {
AzureActiveDirectory(azureAd, "Users and roles", "Azure AD/AccessIT")
AzureApplicationInsights(azureAppi, "Logs, usage, metrics", "Application Insights", "Helps finding errors, and to understand how the application is being used")
}

Rel(sponsor, sepes, "Uses")
Rel(sponsorRep, sepes, "Uses)

Rel(vendor, study, "Uses")
Rel(viewer, study, "Uses")

Rel(spa, api, "Uses")

Rel(sepes, study, "Create and configure study")
Rel(study, datasets, "Create and configure study")
Rel(study, datasetStudy, "Create and configure study")
Rel(sepes, azureAd, "Single-sign-on and user roles")
Rel(sepes, azureAppi, "Sends logs and usage")

@enduml