apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: sepes-api
spec:
  environments:
    - name: prod
      build:
        from: master
    - name: dev
      build:
        from: develop
  components:
    - name: backend
      src: src
      ports:
        - name: http
          port: 80
      publicPort: http
      secrets:
        - AzureAd__ClientId
        - AzureAd__ClientSecret
        - KeyVault_Url
        - AzureVmTempPasswordStorageKeyVault_Url
      environmentConfig:
        - environment: prod
          runAsNonRoot: true
          variables:
            SEPES_HttpOnly: "true"
            DisableMigrations: "false"
            CostAllocationTypeTagName: "CostAllocationType"
            CostAllocationCodeTagName: "CostAllocationCode"
            AllowCorsDomains: "https://frontend-sepes-web-prod.radix.equinor.com,https://sepes.equinor.com"
          replicas: 2
          monitoring: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
        - environment: dev
          runAsNonRoot: true
          variables:
            SEPES_HttpOnly: "true"
            DisableMigrations: "false"
            CostAllocationTypeTagName: "CostAllocationType"
            CostAllocationCodeTagName: "CostAllocationCode"
            AllowCorsDomains: "https://frontend-sepes-web-dev.radix.equinor.com"
          replicas: 2
          monitoring: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
