@startuml "SEPES_Component"
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml


LAYOUT_TOP_DOWN
LAYOUT_WITH_LEGEND


System_Ext(sepes, "SEPES")
System_Ext(opa, "Policy Service", "OPA")

System_Boundary(c1, "Azure"){
    
    Container(azuread, "Azure AD", "Domain controller")
    Container(azurerg, "Azure Resource Groups", "Sandbox for VM")
    Container(azurenet, "Azure Networks", "Controls net of Sandbox")
    Container(azurecat, "Data Catalog", "")
    Container(storageacc, "Storage Account", "Stores copy of Dataset")
    
}
System_Ext(datasrc, "Data Source")

Rel(sepes, azuread, "Logs in to")
Rel(sepes, azurenet, "Creates")
Rel(sepes, azurerg, "Creates")
Rel(sepes, storageacc, "Creates")
Rel_L(storageacc, azurecat, "Requests data")
Rel(azurecat, datasrc, "")
Rel_U(azurecat,opa, "Defines")

@enduml