@startuml "Information_Flow_Request"
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml


LAYOUT_LEFT_RIGHT
LAYOUT_WITH_LEGEND

Container(frontend, "Frontend", "React/Javascript")
Container(backend, "Study Controller", "Dotnet")
Container(azure, "Azure", "Cloud Service")
Container(studyservice, "Study Service", "C#")
Container(podservice, "Pod Service", "C#")

Rel(frontend,backend,"Sends model","JSON/HTTPS")
Rel(backend,studyservice,"Passes along", "JSON")
'Not quite correct to say instantiates.
Rel(studyservice,podservice,"Instanstiates","JSON")
Rel(podservice, azure, "Applies changes","HTTPS")



@enduml