@startuml "SEPES_Flow"
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml


LAYOUT_TOP_DOWN
LAYOUT_WITH_LEGEND


System_Boundary(c0, "Front End"){
    Container(studio, "Study IO", "Javascript")
    Container(frontstd, "Study Service", "javascript")
    Container(frontmdl, "Study Model", "javascript")
    Container(frontact, "Working Study Model", "Javascript")
}
System_Boundary(c1, "RestAPI"){
    Container(stdcontrol, "Study Controller", "C#")
    Container(stdsrvc, "Study Service","C#")
    Container(podsrvc, "Pod Service","C#")
    Container(stdstore, "StudyStore", "C#")
    ContainerDb(database, "State Storage","MSSQL")
    Container(validation, "Validation Service", "technology")
    Container(OPA, "OPA", "OPA")

}
System_Boundary(c2, "Azure"){
    Container(azure, "Azure", "Cloud Service")

}

Lay_R(c0, c1)
Lay_R(c1, c2)


System_Ext(azure,"Azure API")

Rel(studio, stdcontrol,"Sends changes", "JSON/HTTPS")
Rel(stdcontrol,stdsrvc, "passes on", "JSON")

Rel_R(stdsrvc, podsrvc, "Sends pod","JSON")
Rel(podsrvc, validation, "Sends changes")
Rel(validation, OPA, "Validates against")

Rel(frontstd,frontmdl, "")
Rel(frontmdl,frontact, "")
Rel(frontact,frontstd, "")


Rel_U(podsrvc,azure, "Updates")


@enduml